name: C:\Users\idole\Project folder\FastAPI\.conda
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - _openmp_mutex=4.5
  - alembic=1.17.1
  - annotated-types=0.6.0
  - anyio=4.10.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - bcrypt=3.2.0
  - black=25.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cffi=2.0.0
  - click=8.2.1
  - colorama=0.4.6
  - cryptography=46.0.3
  - dnspython=2.4.2
  - ecdsa=0.19.1
  - email-validator=2.3.0
  - expat=2.7.1
  - fastapi=0.116.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - greenlet=3.2.4
  - h11=0.16.0
  - icu=75.1
  - idna=3.7
  - krb5=1.21.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgomp=15.2.0
  - libkrb5=1.21.3
  - libmpdec=4.0.0
  - libpq=18.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libzlib=1.3.1
  - mako=1.3.10
  - markupsafe=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mypy_extensions=1.0.0
  - openssl=3.5.4
  - packaging=25.0
  - passlib=1.7.4
  - pathspec=0.12.1
  - pip=25.2
  - platformdirs=4.3.7
  - psycopg=3.2.10
  - psycopg-c=3.2.10
  - psycopg-pool=3.2.6
  - pyasn1=0.6.1
  - pycparser=2.23
  - pydantic=2.11.9
  - pydantic-core=2.33.2
  - pydantic-settings=2.10.1
  - pyjwt=2.10.1
  - python=3.13.7
  - python-dotenv=1.1.0
  - python-jose=3.5.0
  - python-multipart=0.0.20
  - python_abi=3.13
  - rsa=4.9.1
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.0
  - sqlalchemy=2.0.43
  - sqlite=3.50.2
  - starlette=0.47.3
  - tk=8.6.15
  - typing-extensions=4.15.0
  - typing-inspection=0.4.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - uvicorn=0.35.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - psycopg2==2.9.11
prefix: C:\Users\idole\Project folder\FastAPI\.conda
