name: fastapi-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - sqlalchemy
  - alembic
  - psycopg
  - psycopg-c
  - psycopg-pool
  - fastapi
  - uvicorn
  - pydantic
  - pydantic-settings
  - python-dotenv
  - python-multipart
  - email-validator
  # - passlib==1.7.4
  # - cryptography
  # - pyjwt


  - pip:
    - passlib==1.7.4  
    - bcrypt          
    - cryptography    
    - pyjwt          

