name: fastapi-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - sqlalchemy
  - alembic
  - psycopg
  - psycopg-c
  - psycopg-pool
  - fastapi
  - uvicorn
  - pydantic
  - pydantic-settings
  - python-dotenv
  - python-multipart
  - email-validator
  - passlib
  - bcrypt
  - cryptography
  - pyjwt
  

  - pip:
      - psycopg2-binary==2.9.11

